server:
  servlet:
    session:
      timeout: 30m
  port: 8082
---
spring:
  thymeleaf:
    cache: false
  security:
    oauth2:
      client:
        registration:
          login-client:
            provider: spring
            client-id: login-client
            client-secret: openid-connect
            client-authentication-method: client_secret_basic
            authorization-grant-type: authorization_code
            redirect-uri: http://127.0.0.1:8082/login/oauth2/code/login-client
            scope: openid,profile
            client-name: Spring

        provider:
          spring:
            authorizationUri: http://localhost:8081/oauth2/authorize
            token-uri: http://localhost:8081/oauth2/token
            jwk-set-uri: http://localhost:8081/oauth2/jwks
---
logging:
  level:
    org.springframework.security: debug