server:
  port: 8080

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: DEBUG

spring:
  thymeleaf:
    cache: false
  security:
    oauth2:
      client:
        registration:
          gitee:
            client-id: 1d8fd19d4c177fcc59d532d914566a008e72a647711a32481bb2c2c005a97872
            client-secret: 1c4b2c99bffbbfffb9e15efe9a50d0f64b309922150bd48fc63b546abcdcc97e
            #            ClientAuthenticationMethod 预定义值
            client-authentication-method: client_secret_basic
            #            AuthorizationGrantType 预定义值
            authorization-grant-type: authorization_code
            redirect-uri: http://127.0.0.1:8080/login/oauth2/code/gitee
            scope: user_info
            #            自动构造登录页时，显示的名字
            client-name: Gitee
          github:
            client-id: your-client-id
            client-secret: your-client-secret
        provider:
          gitee:
            authorization-uri: https://gitee.com/oauth/authorize
            token-uri: https://gitee.com/oauth/token
            user-info-uri: https://gitee.com/api/v5/user
            userNameAttribute: name

